### ISSUE TITLE
how to make it work with discord

### ISSUE THREAD

**Issue by rastogiujj12** [TiagoMarinho/Soph#15]
Hey, I have set up https://github.com/AUTOMATIC1111/stable-diffusion-webui, and it's working fine, I have also created config.json and serverlist.json 
when I run the code, and it displays "Ready! Logged in as <bot name>" but I cannot run the commands. I believe am probably missing some steps in setting up the discord bot, any help is greatly appreciated.
Thanks in advance.

**Comment by TiagoMarinho** [comment]
I apologize for not making this clearer in the installation instructions, but you have to run `node src/deploy-commands.js` to register the slash commands for the bot when running it for the first time.

Hopefully that fixes it. If you have any further questions please don't hesitate to ask!
