### ISSUE TITLE
Decouple button functionality from `src/events/button.js`

### ISSUE THREAD

**Issue by TiagoMarinho** [TiagoMarinho/Soph#38]
Would be good to have each button its own function/file, so that code could be more modular. Right now every button is contained into `src/events/button.js` and it's getting hard to further extend it.

The person implementing this can judge for themselves what would be the best way to structure this so that it makes sense.

**Comment by David-Mastalski** [comment]
So, instead of one button.js component that performs various events, you would like to create several buttons where each button will be responsible for something different? I can take care of it if you want
