### ISSUE TITLE
Negative Prompt Default is not used

### ISSUE THREAD

**Issue by LulzRose** [TiagoMarinho/Soph#41]
Easy to recreate, when a negative prompt is set in defaults.json it is not used by the bot during generations.

defaults.json:
![image](https://github.com/TiagoMarinho/Soph/assets/33618233/e30e9ee8-28ce-456a-af12-6c72b9029aca)

Terminal output:
![image](https://github.com/TiagoMarinho/Soph/assets/33618233/f15c90b3-c437-4e50-81b5-acd7ae8d3448)

**Comment by TiagoMarinho** [comment]
Good catch, will work on it asap

My guess is that the "prompt variations" feature (`{ prompt1 | prompt2 | prompt3 }`) from `requestBatch` results in it feeding an empty string to `requestImage`
